name: Build Release Binaries
permissions:
  contents: write

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Display the version of go that we have installed
        run: go version

      - name: Display the release tag
        run: echo ${{ github.event.release.tag_name }}

      - name: Install go-licenses
        run: go install github.com/google/go-licenses@latest
        shell: bash

      - name: Build the executables
        run: ./build-release-binaries.sh ${{ github.event.release.tag_name }}

      - name: List the executables
        run: ls -l ./release

      - name: Upload the binaries
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./release/contrack-*
          file_glob: true
